<?php

// Register "Configuration" field group
acf_add_local_field_group( array(
    'key'                   => 'group_styles_configuration',
    'title'                 => __( 'Configuration', 'pilopress' ),
    'fields'                => array(

        // Typography Tab
        array(
            'key'               => 'field_typography',
            'label'             => __( 'Typography', 'pilopress' ),
            'name'              => '',
            'type'              => 'tab',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '',
                'class' => '',
                'id'    => '',
            ),
            'acfe_permissions'  => '',
            'placement'         => 'top',
            'endpoint'          => 0,
        ),

        // Body classes
        array(
            'key'                 => 'field_pip_body_classes',
            'label'               => '',
            'name'                => 'pip_body_classes',
            'type'                => 'group',
            'instructions'        => '',
            'required'            => 0,
            'conditional_logic'   => 0,
            'wrapper'             => array(
                'width' => '',
                'class' => '',
                'id'    => '',
            ),
            'acfe_permissions'    => '',
            'layout'              => 'row',
            'acfe_seamless_style' => 0,
            'acfe_group_modal'    => 0,
            'sub_fields'          => array(
                array(
                    'key'               => 'field_body_classes',
                    'label'             => __( 'Body', 'pilopress' ),
                    'name'              => 'body_classes',
                    'type'              => 'text',
                    'instructions'      => __( 'Class(es) to apply to the body tag, for default configuration.', 'pilopress' ),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_permissions'  => '',
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
            ),
        ),

        // Typography
        array(
            'key'                           => 'field_pip_typography',
            'label'                         => '',
            'name'                          => 'pip_typography',
            'type'                          => 'repeater',
            'instructions'                  => '',
            'required'                      => 0,
            'conditional_logic'             => 0,
            'wrapper'                       => array(
                'width' => '',
                'class' => '',
                'id'    => '',
            ),
            'acfe_permissions'              => '',
            'acfe_repeater_stylised_button' => 1,
            'collapsed'                     => '',
            'min'                           => 0,
            'max'                           => 0,
            'layout'                        => 'table',
            'button_label'                  => __( 'Add typography', 'pilopress' ),
            'sub_fields'                    => array(
                array(
                    'key'               => 'field_typography_label',
                    'label'             => __( 'Label', 'pilopress' ),
                    'name'              => 'label',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '20',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_permissions'  => '',
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_typography_class_name',
                    'label'             => __( 'Class name', 'pilopress' ),
                    'name'              => 'class_name',
                    'type'              => 'acfe_slug',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '20',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_permissions'  => '',
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_typography_classes',
                    'label'             => __( 'Class(es) to apply', 'pilopress' ),
                    'name'              => 'classes_to_apply',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '40',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_permissions'  => '',
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_typography_add_to_editor',
                    'label'             => __( 'Add to editor ?', 'pilopress' ),
                    'name'              => 'add_to_editor',
                    'type'              => 'true_false',
                    'instructions'      => __( 'Needs TinyMCE Module', 'pilopress' ),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '20',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_permissions'  => '',
                    'message'           => '',
                    'default_value'     => 1,
                    'ui'                => 1,
                    'ui_on_text'        => '',
                    'ui_off_text'       => '',
                ),
            ),
        ),

        // Colors Tab
        array(
            'key'               => 'field_font_color',
            'label'             => __( 'Colors', 'pilopress' ),
            'name'              => '',
            'type'              => 'tab',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '',
                'class' => '',
                'id'    => '',
            ),
            'acfe_permissions'  => '',
            'placement'         => 'top',
            'endpoint'          => 0,
        ),

        // Simple colors
        array(
            'key'                           => 'field_pip_simple_colors',
            'label'                         => __( 'Simple colors', 'pilopress' ),
            'name'                          => 'pip_simple_colors',
            'type'                          => 'repeater',
            'instructions'                  => '',
            'required'                      => 0,
            'conditional_logic'             => 0,
            'wrapper'                       => array(
                'width' => '',
                'class' => '',
                'id'    => '',
            ),
            'acfe_permissions'              => '',
            'acfe_repeater_stylised_button' => 1,
            'collapsed'                     => '',
            'min'                           => 0,
            'max'                           => 0,
            'layout'                        => 'table',
            'button_label'                  => __( 'Add simple color', 'pilopress' ),
            'sub_fields'                    => array(
                array(
                    'key'               => 'field_simple_color_label',
                    'label'             => __( 'Label', 'pilopress' ),
                    'name'              => 'label',
                    'type'              => 'text',
                    'instructions'      => __( 'Visible in editor dropdown', 'pilopress' ),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_permissions'  => '',
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_simple_color_name',
                    'label'             => __( 'Name', 'pilopress' ),
                    'name'              => 'name',
                    'type'              => 'acfe_slug',
                    'instructions'      => __( 'Slug of the color', 'pilopress' ),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_permissions'  => '',
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_simple_color_value',
                    'label'             => __( 'Value', 'pilopress' ),
                    'name'              => 'value',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_permissions'  => '',
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_simple_color_add_to_editor',
                    'label'             => __( 'Add to editor ?', 'pilopress' ),
                    'name'              => 'add_to_editor',
                    'type'              => 'true_false',
                    'instructions'      => __( 'Needs TinyMCE Module', 'pilopress' ),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_permissions'  => '',
                    'message'           => '',
                    'default_value'     => 1,
                    'ui'                => 1,
                    'ui_on_text'        => '',
                    'ui_off_text'       => '',
                ),
            ),
        ),

        // Colors with shades
        array(
            'key'                           => 'field_pip_colors_shades',
            'label'                         => __( 'Colors with shades', 'pilopress' ),
            'name'                          => 'pip_colors_shades',
            'type'                          => 'repeater',
            'instructions'                  => '',
            'required'                      => 0,
            'conditional_logic'             => 0,
            'wrapper'                       => array(
                'width' => '',
                'class' => '',
                'id'    => '',
            ),
            'acfe_permissions'              => '',
            'acfe_repeater_stylised_button' => 1,
            'collapsed'                     => 'field_colors_shades_color_name',
            'min'                           => 0,
            'max'                           => 0,
            'layout'                        => 'table',
            'button_label'                  => __( 'Add color with shades', 'pilopress' ),
            'sub_fields'                    => array(
                array(
                    'key'               => 'field_colors_shades_color_name',
                    'label'             => __( 'Color name', 'pilopress' ),
                    'name'              => 'color_name',
                    'type'              => 'acfe_slug',
                    'instructions'      => __( '<code>gray</code> in <code>text-gray-500</code>', 'pilopress' ),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '25',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_permissions'  => '',
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'                           => 'field_colors_shades_shades',
                    'label'                         => __( 'Shades', 'pilopress' ),
                    'name'                          => 'shades',
                    'type'                          => 'repeater',
                    'instructions'                  => '',
                    'required'                      => 0,
                    'conditional_logic'             => 0,
                    'wrapper'                       => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_permissions'              => '',
                    'acfe_repeater_stylised_button' => 0,
                    'collapsed'                     => '',
                    'min'                           => 0,
                    'max'                           => 0,
                    'layout'                        => 'table',
                    'button_label'                  => __( 'Add shade', 'pilopress' ),
                    'sub_fields'                    => array(
                        array(
                            'key'               => 'field_shade_label',
                            'label'             => __( 'Label', 'pilopress' ),
                            'name'              => 'label',
                            'type'              => 'text',
                            'instructions'      => __( 'Visible in editor dropdown', 'pilopress' ),
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'acfe_permissions'  => '',
                            'default_value'     => '',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'maxlength'         => '',
                        ),
                        array(
                            'key'               => 'field_shade_name',
                            'label'             => __( 'Shade name', 'pilopress' ),
                            'name'              => 'shade_name',
                            'type'              => 'text',
                            'instructions'      => __( '<code>500</code> in <code>text-gray-500</code>', 'pilopress' ),
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'acfe_permissions'  => '',
                            'default_value'     => '',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'maxlength'         => '',
                        ),
                        array(
                            'key'               => 'field_shade_value',
                            'label'             => __( 'Value', 'pilopress' ),
                            'name'              => 'value',
                            'type'              => 'text',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'acfe_permissions'  => '',
                            'default_value'     => '',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'maxlength'         => '',
                        ),
                        array(
                            'key'               => 'field_shade_add_to_editor',
                            'label'             => __( 'Add to editor ?', 'pilopress' ),
                            'name'              => 'add_to_editor',
                            'type'              => 'true_false',
                            'instructions'      => __( 'Needs TinyMCE Module', 'pilopress' ),
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'acfe_permissions'  => '',
                            'message'           => '',
                            'default_value'     => 1,
                            'ui'                => 1,
                            'ui_on_text'        => '',
                            'ui_off_text'       => '',
                        ),
                    ),
                ),
            ),
        ),

        // Buttons
        array(
            'key'               => 'field_tab_button',
            'label'             => __( 'Buttons', 'pilopress' ),
            'name'              => '',
            'type'              => 'tab',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '',
                'class' => '',
                'id'    => '',
            ),
            'acfe_permissions'  => '',
            'placement'         => 'top',
            'endpoint'          => 0,
        ),
        array(
            'key'                           => 'field_pip_button',
            'label'                         => '',
            'name'                          => 'pip_button',
            'type'                          => 'repeater',
            'instructions'                  => '',
            'required'                      => 0,
            'conditional_logic'             => 0,
            'wrapper'                       => array(
                'width' => '',
                'class' => '',
                'id'    => '',
            ),
            'acfe_permissions'              => '',
            'acfe_repeater_stylised_button' => 1,
            'collapsed'                     => '',
            'min'                           => 0,
            'max'                           => 0,
            'layout'                        => 'block',
            'button_label'                  => __( 'Add button style', 'pilopress' ),
            'sub_fields'                    => array(
                array(
                    'key'               => 'field_custom_button_label',
                    'label'             => __( 'Label', 'pilopress' ),
                    'name'              => 'label',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '20',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_permissions'  => '',
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_custom_button_class',
                    'label'             => __( 'Class name', 'pilopress' ),
                    'name'              => 'class_name',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '20',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_permissions'  => '',
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_custom_button_classes',
                    'label'             => __( 'Class(es) to apply', 'pilopress' ),
                    'name'              => 'classes_to_apply',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '40',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_permissions'  => '',
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_custom_button_add_to_editor',
                    'label'             => __( 'Add to editor ?', 'pilopress' ),
                    'name'              => 'add_to_editor',
                    'type'              => 'true_false',
                    'instructions'      => __( 'Needs TinyMCE Module', 'pilopress' ),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '20',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_permissions'  => '',
                    'message'           => '',
                    'default_value'     => 1,
                    'ui'                => 1,
                    'ui_on_text'        => '',
                    'ui_off_text'       => '',
                ),
                array(
                    'key'                           => 'field_custom_button_states',
                    'label'                         => __( 'States', 'pilopress' ),
                    'name'                          => 'states',
                    'type'                          => 'repeater',
                    'instructions'                  => '',
                    'required'                      => 0,
                    'conditional_logic'             => 0,
                    'wrapper'                       => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_permissions'              => '',
                    'acfe_repeater_stylised_button' => 0,
                    'collapsed'                     => '',
                    'min'                           => 0,
                    'max'                           => 0,
                    'layout'                        => 'table',
                    'button_label'                  => __( 'Add button state', 'pilopress' ),
                    'sub_fields'                    => array(
                        array(
                            'key'               => 'field_state_type',
                            'label'             => __( 'Type', 'pilopress' ),
                            'name'              => 'type',
                            'type'              => 'select',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '20',
                                'class' => '',
                                'id'    => '',
                            ),
                            'acfe_permissions'  => '',
                            'choices'           => array(
                                'hover'  => 'hover',
                                'active' => 'active',
                                'focus'  => 'focus',
                            ),
                            'default_value'     => false,
                            'allow_null'        => 0,
                            'multiple'          => 0,
                            'ui'                => 0,
                            'return_format'     => 'value',
                            'ajax'              => 0,
                            'placeholder'       => '',
                        ),
                        array(
                            'key'               => 'field_state_classes_to_apply',
                            'label'             => __( 'Class(es) to apply', 'pilopress' ),
                            'name'              => 'classes_to_apply',
                            'type'              => 'text',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '80',
                                'class' => '',
                                'id'    => '',
                            ),
                            'acfe_permissions'  => '',
                            'default_value'     => '',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'maxlength'         => '',
                        ),
                    ),
                ),
            ),
        ),

        // Breakpoints
        array(
            'key'               => 'field_tab_screens',
            'label'             => __( 'Breakpoints', 'pilopress' ),
            'name'              => '',
            'type'              => 'tab',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '',
                'class' => '',
                'id'    => '',
            ),
            'acfe_permissions'  => '',
            'placement'         => 'top',
            'endpoint'          => 0,
        ),
        array(
            'key'                           => 'field_pip_screens',
            'label'                         => '',
            'name'                          => 'pip_screens',
            'type'                          => 'repeater',
            'instructions'                  => '',
            'required'                      => 0,
            'conditional_logic'             => 0,
            'wrapper'                       => array(
                'width' => '',
                'class' => '',
                'id'    => '',
            ),
            'acfe_permissions'              => '',
            'acfe_repeater_stylised_button' => 1,
            'collapsed'                     => '',
            'min'                           => 0,
            'max'                           => 0,
            'layout'                        => 'table',
            'button_label'                  => __( 'Add breakpoint', 'pilopress' ),
            'sub_fields'                    => array(
                array(
                    'key'               => 'field_screen_name',
                    'label'             => __( 'Name', 'pilopress' ),
                    'name'              => 'name',
                    'type'              => 'acfe_slug',
                    'instructions'      => '',
                    'required'          => 1,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_permissions'  => '',
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_screen_value',
                    'label'             => __( 'Value', 'pilopress' ),
                    'name'              => 'value',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 1,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_permissions'  => '',
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
            ),
        ),

        // Container
        array(
            'key'               => 'field_tab_container',
            'label'             => __( 'Container', 'pilopress' ),
            'name'              => '',
            'type'              => 'tab',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '',
                'class' => '',
                'id'    => '',
            ),
            'acfe_permissions'  => '',
            'placement'         => 'top',
            'endpoint'          => 0,
        ),
        array(
            'key'                 => 'field_pip_container',
            'label'               => '',
            'name'                => 'pip_container',
            'type'                => 'group',
            'instructions'        => '',
            'required'            => 0,
            'conditional_logic'   => 0,
            'wrapper'             => array(
                'width' => '',
                'class' => '',
                'id'    => '',
            ),
            'acfe_permissions'    => '',
            'layout'              => 'row',
            'acfe_seamless_style' => 1,
            'acfe_group_modal'    => 0,
            'sub_fields'          => array(
                array(
                    'key'               => 'field_container_center',
                    'label'             => __( 'Center container', 'pilopress' ),
                    'name'              => 'center_container',
                    'type'              => 'true_false',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_permissions'  => '',
                    'message'           => '',
                    'default_value'     => 0,
                    'ui'                => 1,
                    'ui_on_text'        => '',
                    'ui_off_text'       => '',
                ),
                array(
                    'key'               => 'field_container_add_padding_value',
                    'label'             => __( 'Add horizontal padding', 'pilopress' ),
                    'name'              => 'add_horizontal_padding',
                    'type'              => 'true_false',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_permissions'  => '',
                    'message'           => '',
                    'default_value'     => 0,
                    'ui'                => 1,
                    'ui_on_text'        => '',
                    'ui_off_text'       => '',
                ),
                array(
                    'key'               => 'field_container_padding_value',
                    'label'             => __( 'Horizontal padding value', 'pilopress' ),
                    'name'              => 'padding_value',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field'    => 'field_container_add_padding_value',
                                'operator' => '==',
                                'value'    => '1',
                            ),
                        ),
                    ),
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_permissions'  => '',
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
            ),
        ),

    ),
    'location'              => array(
        array(
            array(
                'param'    => 'options_page',
                'operator' => '==',
                'value'    => 'pip-styles-configuration',
            ),
        ),
    ),
    'menu_order'            => 0,
    'position'              => 'normal',
    'style'                 => 'seamless',
    'label_placement'       => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen'        => '',
    'active'                => true,
    'description'           => '',
    'acfe_display_title'    => '',
    'acfe_autosync'         => '',
    'acfe_permissions'      => '',
    'acfe_form'             => 0,
    'acfe_meta'             => '',
    'acfe_note'             => '',
    'acfe_categories'       => array(
        'options' => 'Options',
    ),
) );
